### ISSUE TITLE
博主 你用静态变量缓存了表达式树 会有并发问题吧！！

### ISSUE THREAD

**Issue by Skolley** [bieyuan/.net-core-DTO#7]
**private static Func<TSource, TTarget> MapFunc { get; set; }**

        private static Action<TSource, TTarget> MapAction { get; set; }

        /// <summary>
        /// 将对象TSource转换为TTarget
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static TTarget Map(TSource source)
        {
            **if (MapFunc == null)
                MapFunc = GetMapFunc();

            return MapFunc(source);**
        }

**Comment by bieyuan** [comment]
已经 调整成 运行时常量 readonly  解决
